---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
  labels:
    app: wordpress
  namespace: backend
spec:
  selector:
    matchLabels:
      name: wordpress-db
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: wordpress-db
        tier: backend
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /Users/draju1980/out/wordpress-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      name: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: "/var/www/html"
      volumes:
      - name: wordpress-persistent-storage
        hostPath:
          path: /Users/draju1980/out/wordpress
