---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: backend
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    name: wordpress-db
    tier: backend
  clusterIP: None
